#!/bin/bash

# Cập nhật danh sách gói và cài đặt các gói cần thiết
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
sudo apt update
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common

# Thêm kho Docker vào hệ thống
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Cập nhật lại danh sách gói và cài đặt Docker
sudo apt update
apt-cache policy docker-ce
sudo apt install -y docker-ce

# Khởi động Docker và cấu hình để tự động khởi động khi máy chủ khởi động
sudo systemctl start docker
sudo systemctl enable docker

# Cài đặt Docker Compose
mkdir -p ~/.docker/cli-plugins/
curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
chmod +x ~/.docker/cli-plugins/docker-compose

# Kiểm tra phiên bản Docker và Docker Compose
docker --version
docker compose version
