services:
  express-app:
    container_name: core-service-express
    image: <to-be-replaced-in-cicd>
    ports:
      - "8000:8000"
    restart: always
    env-file: 
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true